version: '2'


services:

  hh-trainer:
    image: hyperiongray/hh-deep-deep:0.1.4  # update below too!
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deep-deep-jobs:/opt/hh-deep-deep/deep-deep-jobs
    command:
      - hh-deep-deep-service
      - trainer
      - --kafka-host=hh-kafka
      - --docker-image=hyperiongray/deep-deep-hh:0.1.0
      - --host-root=${PWD}

  hh-crawler:
    image: hyperiongray/hh-deep-deep:0.1.4
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dd-jobs:/opt/hh-deep-deep/dd-jobs
    command:
      - hh-deep-deep-service
      - crawler
      - --kafka-host=hh-kafka
      - --docker-image=hyperiongray/dd-crawler-hh:0.1.0
      - --host-root=${PWD}

  hh-modeler:
    image: hyperiongray/hh-page-clf:0.3.1  # update git submodule too
    restart: always
    network_mode: host
    volumes:
      - ./models:/models
    command:
      - hh-page-clf-service
      - --kafka-host=hh-kafka
      - --random-pages=/models/random-pages.jl.gz
      - --lda=/models/lda.pkl

  tor-proxy:
    image: hyperiongray/tor-proxy:0.1.1
    network_mode: host

  tor-privoxy:
    image: jess/privoxy
    network_mode: host
