version: '2'


services:

  hh-trainer:
    image: docker.hyperiongray.com/hh-deep-deep:0.0.2  # update below too!
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deep-deep-jobs:/opt/hh-deep-deep/deep-deep-jobs
    command:
      - hh-deep-deep-service
      - trainer
      - --kafka-host=hh-kafka
      - --docker-image=docker.hyperiongray.com/deep-deep:0.0.2
      - --host-root=${PWD}

  hh-crawler:
    image: docker.hyperiongray.com/hh-deep-deep:0.0.2
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dd-jobs:/opt/hh-deep-deep/dd-jobs
    command:
      - hh-deep-deep-service
      - crawler
      - --kafka-host=hh-kafka
      - --docker-image=docker.hyperiongray.com/dd-crawler:0.0.2
      - --host-root=${PWD}

  hh-modeler:
    image: docker.hyperiongray.com/hh-page-clf:0.0.8
    restart: always
    network_mode: host
    command:
      - hh-page-clf-service
      - --kafka-host=hh-kafka
