version: '2'


volumes:
  redis-data: {{}}


services:

  redis:
    image: redis:3.0
    network_mode: bridge
    volumes:
      - redis-data:/data
      - {redis_conf}:/usr/local/etc/redis/redis.conf
    command: [redis-server, /usr/local/etc/redis/redis.conf]

  crawler:
    image: {docker_image}
    external_links: {external_links}
    network_mode: bridge
    volumes:
      - {seeds}:/dd_crawler/seeds.txt
      - {out}:/out
    entrypoint:
      - /dd_crawler/docker/crawl.sh
      - dd_crawler
      - -a
      - seeds=/dd_crawler/seeds.txt
      - -s
      - CLOSESPIDER_ITEMCOUNT={page_limit}
      - -s
      - AUTOPAGER=1
      - -s
      - DOMAIN_LIMIT=1
      - -s
      - HTTP_PROXY={proxy}
      - -s
      - HTTPS_PROXY={proxy}
      - -s
      - FILES_STORE=/out/media
      - -s
      - AUTOLOGIN_ENABLED=1
      - -s
      - AUTOLOGIN_URL=http://autologin:8089
      - -s
      - SCHEDULER_IDLE_BEFORE_CLOSE={idle_before_close}
    dns:
      - 127.0.0.1
    links:
      - redis

  autologin:
    image: hyperiongray/autologin:0.1.4
    network_mode: bridge
    expose:
      - "8089"
